# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[templates]
defer = """{% for file in files %}
zsh-defer source "{{ file }}"
{% endfor %}"""

[plugins.bindkey]
inline = 'bindkey -e'

[plugins.zsh-syntax-highlighting]
github = "zdharma/fast-syntax-highlighting"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-abbr]
github = "olets/zsh-abbr"

[plugins.enhancd]
github = "b4b4r07/enhancd"
apply = ["defer"]

[plugins.dotfiles]
local = "~/.zsh"
use = ["saneopt.zsh", "zstyle.zsh", "env.zsh", "history.zsh", "starship.zsh"]

[plugins.dotfiles-defers]
local = "~/.zsh"
apply = ["defer"]
use = [
  "alias.zsh",
  "fzf.zsh",
  "keybinding.zsh",
  "setting.zsh",
  "zoxide.zsh",
  "hook.zsh",
  "local.zsh",
  "env.zsh",
  "history.zsh",
  "osc133.zsh",
  "broot.zsh",
  "rtx.zsh",
  "chezmoi.zsh",
  "cargo.zsh",
  "go.zsh",
  "direnv.zsh",
  "google-cloud-sdk.zsh",
  "krew.zsh",
]

[plugins.compinit]
inline = 'autoload -Uz compinit && zsh-defer compinit'
