# Use c-j instead of c-b as the prefix
unbind C-b
set -g prefix C-j
bind C-j send-prefix


set -g default-command zsh
set -g status-right "#(uptime|awk '{print $11}') #(date)"
#set -g status-right "%H:%M" # %d-%b-%y
set -g status-left-length 30
#set -g status-left '#[fg=white,bg=black]#H#[fg=white]:#[fg=white][#S#[fg=white]][#[default]]'
#set -g status-right '#[fg=black,bg=cyan,bold] [%Y-%m-%d(%a) %H:%M]#[default]'

# Statusbar properties.
set -g display-time 3000

set -g status-bg black
set -g status-fg cyan

set-window-option -g window-status-current-attr bright,reverse,bold
set-window-option -g window-status-current-bg cyan
set-window-option -g window-status-current-fg black

set -g pane-active-border-fg cyan
set -g pane-active-border-bg black

set-window-option -g utf8 on
set-window-option -g mode-keys vi
set-window-option -g automatic-rename off

#set -g mode-mouse on
#set -g mouse-resize-pane on
set -g mouse-select-pane on
#set -g mouse-select-window o

# prefix + r で設定ファイルを再読み込み
unbind r
bind r source-file ~/.tmux.conf

# vim: ft=tmux
