# Use c-j instead of c-b as the prefix
unbind C-b
set -g prefix C-j
bind C-j send-prefix
#bind t send-prefix
#
set -g default-command zsh
#set -g status-right "#(uptime|awk '{print $11}') #(date)"
set -g status-right "%H:%M" # %d-%b-%y

# Statusbar properties.
set -g display-time 3000
set -g status-bg black
set -g status-fg cyan
set-window-option -g window-status-current-attr bright,reverse,bold
set-window-option -g window-status-current-bg cyan
set-window-option -g window-status-current-fg black

set-window-option -g utf8 on
set-window-option -g mode-keys vi
set-window-option -g automatic-rename off


# copy-mode ^[
unbind ^"["
bind -r ^"[" copy-mode
unbind ^]
bind -r ^] paste-buffer

# vim: ft=tmux
