tap phinze/homebrew-cask

# Homebrewを最新版にアップデート
update

# Formulaを更新
upgrade

install ack
install arangodb
install autoconf
install automake
install autossh
install bash-completion
install bazaar
install bison
install boost
install boost-build
install bsdiff
install bsdmake
install ccache
install cgdb
install cloog
install cloog018
install cmake
install coreutils
install cscope
install curl
install dmd
install docbook
install elasticsearch
install erlang
install flare
install freetype
install gauche
install gcc48
install gcc49
install gdb
install gdbm
install gettext
install ghc
install ghostscript
install gibo
install git
install giter8
install global
install gmp
install gmp4
install gnu-getopt
install gnu-tar
install go
install graphviz
install groonga
install haskell-platform
install htop-osx
install hub
install icu4c
install imagemagick
install ioping
install isl
install isl011
install jansson
install jbig2dec
install jpeg
install jq
install kyoto-cabinet
install kyoto-tycoon
install libev
install libevent
install libident
install libmpc
install libmpc08
install libpng
install libtasn1
install libtiff
install libtool
install libxml2
install libxslt
install libyaml
install little-cms2
install lua
install lv
install maven
install md5sha1sum
install mecab
install mecab-ipadic
install mobile-shell
install mongodb
install mpfr
install mpfr2
install mpio
install msgpack
install msgpack-rpc
install mysql
install nginx
install ngircd
install objective-caml
install oniguruma
install openssl
install ossp-uuid
install packer
install parallel
install pcre
install pkg-config
install postgresql
install proctools
install protobuf
install python
install python3
install qcachegrind
install qt
install rbenv
install readline
install reattach-to-user-namespace
install rebar
install redis
install rename
install riak
install ruby-build
install s3cmd
install sbt
install scala
install scons
install sl
install snappy
install sqlite
install storm
install thrift
install tig
install tmux
install tokyo-cabinet
install tokyo-tyrant
install tree
install v8
install valgrind
install watch
install wget
install xmlto
install xz
install z
install zsh

# インストール
cask install google-chrome
cask install kobito
cask install virtualbox
cask install vagrant

# 不要なファイルを削除
clean
