#!/bin/bash

# SF Symbols icons
ICON_CPU="􀧓"
ICON_MEMORY="􀫦"
ICON_BATTERY_FULL="􀛨"
ICON_BATTERY_CHARGING="􀢋"
ICON_CLOCK="􀐫"
ICON_MUSIC="􀑪"
ICON_POMODORO="􀐱"
ICON_WORKSPACE="􀏟"
ICON_PLAY="􀊄"
ICON_PAUSE="􀊆"
ICON_CALENDAR="􀉉"
ICON_BREAK="􀸲"
ICON_NETWORK_DOWN="􀄩"
ICON_NETWORK_UP="􀄨"
ICON_WIFI="􀙇"
ICON_WIFI_OFF="􀙈"
