onboarding = false

[keys]
prefix = "ctrl+y"
open_notification_target = "ctrl+shift+o"
new_tab = "cmd+t"
new_workspace = "cmd+n"
next_workspace = "ctrl+shift+j"
previous_workspace = "ctrl+shift+k"
next_agent = "ctrl+shift+m"
previous_agent = "ctrl+shift+,"
previous_tab = "ctrl+shift+h"
next_tab = "ctrl+shift+l"
split_vertical = "cmd+d"
cycle_pane_next = ["prefix+o", "prefix+ctrl+o"]
cycle_pane_previous = ["prefix+shift+o", "prefix+ctrl+shift+o"]

[[keys.command]]
key = "cmd+l"
type = "pane"
command = "lazygit"
description = "Open lazygit"

[[keys.command]]
key = "cmd+y"
type = "pane"
command = "yazi"
description = "Open yazi"

[[keys.command]]
key = "cmd+shift+l"
type = "shell"
command = '''exec "${XDG_CONFIG_HOME:-$HOME/.config}/herdr/scripts/open-in-split" lazygit right'''
description = "Open lazygit in split"

[[keys.command]]
key = "cmd+shift+y"
type = "shell"
command = '''exec "${XDG_CONFIG_HOME:-$HOME/.config}/herdr/scripts/open-in-split" yazi right'''
description = "Open yazi in split"

[ui.toast]
delivery = "herdr"

[ui]
show_agent_labels_on_pane_borders = true
prompt_new_tab_name = false
agent_panel_sort = "spaces"
sidebar_max_width = 60
tab_bar_right = [{ type = "zoom" }]

status_indicators = "symbols"
[ui.sidebar.spaces]
rows = [["state_icon", "$repo"], ["branch", "git_status"]]

[ui.sidebar.agents]
rows = [["state_icon", "$repo", "tab"], ["agent", "$updated"]]

[advanced]
scrollback_limit_bytes = 25000000

[session]
resume_agents_on_restore = true

[experimental]
switch_ascii_input_source_in_prefix = true
kitty_graphics = true
