# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[templates]
defer = { value = 'zsh-defer source "{{ file }}"', each = true }

[plugins.compinit]
inline = 'autoload -Uz compinit && zsh-defer compinit'

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.ohmyzsh-lib]
github = "ohmyzsh/ohmyzsh"
dir = "lib"
use = ["clipboard.zsh"]

[plugins.prezto-modules]
github = "sorin-ionescu/prezto"
dir = "modules"
use = ["editor/init.zsh", "history/init.zsh"]

[plugins.asdf]
github = "asdf-vm/asdf"

[plugins.asdf-completion]
github = "asdf-vm/asdf"
dir = "completions"
apply = ["fpath"]

[plugins.zsh-abbrev-zlias]
github = "momo-lab/zsh-abbrev-alias"

[plugins.zsh-z]
github = "agkozak/zsh-z"

[plugins.dotfiles-defers]
local = "~/.zsh"
use = [
    "alias.zsh",
    "fzf.zsh",
    "keybinding.zsh",
    "saneopt.zsh",
    "setting.zsh",
    "zstyle.zsh",
]
