#!/bin/sh

set -eu

if [ "$#" -ne 2 ]; then
  echo "usage: open-in-split <command> <right|down>" >&2
  exit 2
fi

command=$1
direction=$2

case "$direction" in
  right | down) ;;
  *)
    echo "open-in-split: direction must be right or down" >&2
    exit 2
    ;;
esac

herdr_bin=${HERDR_BIN_PATH:-herdr}
target_pane_id=${HERDR_ACTIVE_PANE_ID:-${HERDR_PANE_ID:-}}
target_cwd=${HERDR_ACTIVE_PANE_CWD:-${PWD:-}}

if [ -z "$target_pane_id" ]; then
  echo "open-in-split: no active Herdr pane" >&2
  exit 1
fi

if [ -n "$target_cwd" ]; then
  exec "$herdr_bin" plugin pane open \
    --plugin choplin.split-pane \
    --entrypoint command \
    --placement split \
    --target-pane "$target_pane_id" \
    --direction "$direction" \
    --cwd "$target_cwd" \
    --env "HERDR_SPLIT_COMMAND=$command" \
    --focus
fi

exec "$herdr_bin" plugin pane open \
  --plugin choplin.split-pane \
  --entrypoint command \
  --placement split \
  --target-pane "$target_pane_id" \
  --direction "$direction" \
  --env "HERDR_SPLIT_COMMAND=$command" \
  --focus
