[tools]
java = [
    "openjdk-17",
    "adoptopenjdk-11.0.20+101",
    "openjdk-19",
    "openjdk-21",
    "zulu-8.68.0.21",
]
maven = "3.9"
zig = "0.11"
sbt = "1.9"
gradle = "8"
go = "1.21"
python = "3.11"
node = "20"
